import openpyxl as excel
from openpyxl.styles.borders import Border, Side
from openpyxl.styles.fills import PatternFill, FILL_SOLID
from openpyxl.styles.borders import BORDER_THIN
from openpyxl.styles.colors import BLACK
from Lib.FileSysProcess import FileSysProcess

defaultborder = Border(top=Side(style=BORDER_THIN, color=BLACK), 
                       bottom=Side(style=BORDER_THIN, color=BLACK), 
                       left=Side(style=BORDER_THIN, color=BLACK),
                       right=Side(style=BORDER_THIN, color=BLACK))

class ECell(object):
    cellRange:str
    def __init__(self)->None: 
        self.columnNameList:dict[int,str] ={}  
        self.__createColumnNameList()
        self.cellRange = ""
        return

    def getColumnName(self, columnIndex:int) ->str:
        return self.columnNameList[columnIndex]
    
    def setCellRange(self,rowIndex:int = 0, columnIndex:int = 0, endRowIndex:int = 0,  endColumnIndex:int = 0)->None:
        
        if rowIndex + columnIndex == 0:
            self.cellRange = 'A1'
            return
        
        if rowIndex == endRowIndex:
            endRowIndex = 0
        if columnIndex == endColumnIndex:
            endColumnIndex = 0

        if columnIndex + endRowIndex + endColumnIndex == 0:
            self.cellRange = str(rowIndex) + ':'+ str(rowIndex)
            return

        if rowIndex + endRowIndex + endColumnIndex == 0:
            self.cellRange = self.getColumnName(columnIndex)
            return
        
        if rowIndex + endRowIndex == 0:
            self.cellRange = self.getColumnName(columnIndex) + ':'+ self.getColumnName(endColumnIndex)
            return

        if endRowIndex + endColumnIndex == 0:
            self.cellRange = self.getColumnName(columnIndex) + str(rowIndex)
            return
        
        if endRowIndex != 0 and endColumnIndex == 0:
            self.cellRange = self.getColumnName(columnIndex) + str(rowIndex)+ ':' + self.getColumnName(columnIndex) + str(endRowIndex)
            return
        if endRowIndex == 0 and endColumnIndex != 0:
            self.cellRange = self.getColumnName(columnIndex) + str(rowIndex)+ ':' + self.getColumnName(endColumnIndex) + str(rowIndex)
            return
        self.cellRange = self.getColumnName(columnIndex) + str(rowIndex)+ ':' + self.getColumnName(endColumnIndex) + str(endRowIndex)
        return
    def getCellRange(self) ->str:
        if self.cellRange == '':
            return 'A1'
        else:
            return self.cellRange
        
    def __createColumnNameList(self)->None:
        self.columnNameList.clear()
        self.columnNameList[  1 ] = 'A'
        self.columnNameList[  2 ] = 'B'
        self.columnNameList[  3 ] = 'C'
        self.columnNameList[  4 ] = 'D'
        self.columnNameList[  5 ] = 'E'
        self.columnNameList[  6 ] = 'F'
        self.columnNameList[  7 ] = 'G'
        self.columnNameList[  8 ] = 'H'
        self.columnNameList[  9 ] = 'I'
        self.columnNameList[ 10 ] = 'J'
        self.columnNameList[ 11 ] = 'K'
        self.columnNameList[ 12 ] = 'L'
        self.columnNameList[ 13 ] = 'M'
        self.columnNameList[ 14 ] = 'N'
        self.columnNameList[ 15 ] = 'O'
        self.columnNameList[ 16 ] = 'P'
        self.columnNameList[ 17 ] = 'Q'
        self.columnNameList[ 18 ] = 'R'
        self.columnNameList[ 19 ] = 'S'
        self.columnNameList[ 20 ] = 'T'
        self.columnNameList[ 21 ] = 'U'
        self.columnNameList[ 22 ] = 'V'
        self.columnNameList[ 23 ] = 'W'
        self.columnNameList[ 24 ] = 'X'
        self.columnNameList[ 25 ] = 'Y'
        self.columnNameList[ 26 ] = 'Z'
        self.columnNameList[ 27 ] = 'AA'
        self.columnNameList[ 28 ] = 'AB'
        self.columnNameList[ 29 ] = 'AC'
        self.columnNameList[ 30 ] = 'AD'
        self.columnNameList[ 31 ] = 'AE'
        self.columnNameList[ 32 ] = 'AF'
        self.columnNameList[ 33 ] = 'AG'
        self.columnNameList[ 34 ] = 'AH'
        self.columnNameList[ 35 ] = 'AI'
        self.columnNameList[ 36 ] = 'AJ'
        self.columnNameList[ 37 ] = 'AK'
        self.columnNameList[ 38 ] = 'AL'
        self.columnNameList[ 39 ] = 'AM'
        self.columnNameList[ 40 ] = 'AN'
        self.columnNameList[ 41 ] = 'AO'
        self.columnNameList[ 42 ] = 'AP'
        self.columnNameList[ 43 ] = 'AQ'
        self.columnNameList[ 44 ] = 'AR'
        self.columnNameList[ 45 ] = 'AS'
        self.columnNameList[ 46 ] = 'AT'
        self.columnNameList[ 47 ] = 'AU'
        self.columnNameList[ 48 ] = 'AV'
        self.columnNameList[ 49 ] = 'AW'
        self.columnNameList[ 50 ] = 'AX'
        self.columnNameList[ 51 ] = 'AY'
        self.columnNameList[ 52 ] = 'AZ'
        self.columnNameList[ 53 ] = 'BA'
        self.columnNameList[ 54 ] = 'BB'
        self.columnNameList[ 55 ] = 'BC'
        self.columnNameList[ 56 ] = 'BD'
        self.columnNameList[ 57 ] = 'BE'
        self.columnNameList[ 58 ] = 'BF'
        self.columnNameList[ 59 ] = 'BG'
        self.columnNameList[ 60 ] = 'BH'
        self.columnNameList[ 61 ] = 'BI'
        self.columnNameList[ 62 ] = 'BJ'
        self.columnNameList[ 63 ] = 'BK'
        self.columnNameList[ 64 ] = 'BL'
        self.columnNameList[ 65 ] = 'BM'
        self.columnNameList[ 66 ] = 'BN'
        self.columnNameList[ 67 ] = 'BO'
        self.columnNameList[ 68 ] = 'BP'
        self.columnNameList[ 69 ] = 'BQ'
        self.columnNameList[ 70 ] = 'BR'
        self.columnNameList[ 71 ] = 'BS'
        self.columnNameList[ 72 ] = 'BT'
        self.columnNameList[ 73 ] = 'BU'
        self.columnNameList[ 74 ] = 'BV'
        self.columnNameList[ 75 ] = 'BW'
        self.columnNameList[ 76 ] = 'BX'
        self.columnNameList[ 77 ] = 'BY'
        self.columnNameList[ 78 ] = 'BZ'
        self.columnNameList[ 79 ] = 'CA'
        self.columnNameList[ 80 ] = 'CB'
        self.columnNameList[ 81 ] = 'CC'
        self.columnNameList[ 82 ] = 'CD'
        self.columnNameList[ 83 ] = 'CE'
        self.columnNameList[ 84 ] = 'CF'
        self.columnNameList[ 85 ] = 'CG'
        self.columnNameList[ 86 ] = 'CH'
        self.columnNameList[ 87 ] = 'CI'
        self.columnNameList[ 88 ] = 'CJ'
        self.columnNameList[ 89 ] = 'CK'
        self.columnNameList[ 90 ] = 'CL'
        self.columnNameList[ 91 ] = 'CM'
        self.columnNameList[ 92 ] = 'CN'
        self.columnNameList[ 93 ] = 'CO'
        self.columnNameList[ 94 ] = 'CP'
        self.columnNameList[ 95 ] = 'CQ'
        self.columnNameList[ 96 ] = 'CR'
        self.columnNameList[ 97 ] = 'CS'
        self.columnNameList[ 98 ] = 'CT'
        self.columnNameList[ 99 ] = 'CU'
        self.columnNameList[ 100] = 'CV'
        self.columnNameList[ 101] = 'CW'
        self.columnNameList[ 102] = 'CX'
        self.columnNameList[ 103] = 'CY'
        self.columnNameList[ 104] = 'CZ'
        self.columnNameList[ 105] = 'DA'
        self.columnNameList[ 106] = 'DB'
        self.columnNameList[ 107] = 'DC'
        self.columnNameList[ 108] = 'DD'
        self.columnNameList[ 109] = 'DE'
        self.columnNameList[ 110] = 'DF'
        self.columnNameList[ 111] = 'DG'
        self.columnNameList[ 112] = 'DH'
        self.columnNameList[ 113] = 'DI'
        self.columnNameList[ 114] = 'DJ'
        self.columnNameList[ 115] = 'DK'
        self.columnNameList[ 116] = 'DL'
        self.columnNameList[ 117] = 'DM'
        self.columnNameList[ 118] = 'DN'
        self.columnNameList[ 119] = 'DO'
        self.columnNameList[ 120] = 'DP'
        self.columnNameList[ 121] = 'DQ'
        self.columnNameList[ 122] = 'DR'
        self.columnNameList[ 123] = 'DS'
        self.columnNameList[ 124] = 'DT'
        self.columnNameList[ 125] = 'DU'
        self.columnNameList[ 126] = 'DV'
        self.columnNameList[ 127] = 'DW'
        self.columnNameList[ 128] = 'DX'
        self.columnNameList[ 129] = 'DY'
        self.columnNameList[ 130] = 'DZ'
        self.columnNameList[ 131] = 'EA'
        self.columnNameList[ 132] = 'EB'
        self.columnNameList[ 133] = 'EC'
        self.columnNameList[ 134] = 'ED'
        self.columnNameList[ 135] = 'EE'
        self.columnNameList[ 136] = 'EF'
        self.columnNameList[ 137] = 'EG'
        self.columnNameList[ 138] = 'EH'
        self.columnNameList[ 139] = 'EI'
        self.columnNameList[ 140] = 'EJ'
        self.columnNameList[ 141] = 'EK'
        self.columnNameList[ 142] = 'EL'
        self.columnNameList[ 143] = 'EM'
        self.columnNameList[ 144] = 'EN'
        self.columnNameList[ 145] = 'EO'
        self.columnNameList[ 146] = 'EP'
        self.columnNameList[ 147] = 'EQ'
        self.columnNameList[ 148] = 'ER'
        self.columnNameList[ 149] = 'ES'
        self.columnNameList[ 150] = 'ET'
        self.columnNameList[ 151] = 'EU'
        self.columnNameList[ 152] = 'EV'
        self.columnNameList[ 153] = 'EW'
        self.columnNameList[ 154] = 'EX'
        self.columnNameList[ 155] = 'EY'
        self.columnNameList[ 156] = 'EZ'
        self.columnNameList[ 157] = 'FA'
        self.columnNameList[ 158] = 'FB'
        self.columnNameList[ 159] = 'FC'
        self.columnNameList[ 160] = 'FD'
        self.columnNameList[ 161] = 'FE'
        self.columnNameList[ 162] = 'FF'
        self.columnNameList[ 163] = 'FG'
        self.columnNameList[ 164] = 'FH'
        self.columnNameList[ 165] = 'FI'
        self.columnNameList[ 166] = 'FJ'
        self.columnNameList[ 167] = 'FK'
        self.columnNameList[ 168] = 'FL'
        self.columnNameList[ 169] = 'FM'
        self.columnNameList[ 170] = 'FN'
        self.columnNameList[ 171] = 'FO'
        self.columnNameList[ 172] = 'FP'
        self.columnNameList[ 173] = 'FQ'
        self.columnNameList[ 174] = 'FR'
        self.columnNameList[ 175] = 'FS'
        self.columnNameList[ 176] = 'FT'
        self.columnNameList[ 177] = 'FU'
        self.columnNameList[ 178] = 'FV'
        self.columnNameList[ 179] = 'FW'
        self.columnNameList[ 180] = 'FX'
        self.columnNameList[ 181] = 'FY'
        self.columnNameList[ 182] = 'FZ'
        self.columnNameList[ 183] = 'GA'
        self.columnNameList[ 184] = 'GB'
        self.columnNameList[ 185] = 'GC'
        self.columnNameList[ 186] = 'GD'
        self.columnNameList[ 187] = 'GE'
        self.columnNameList[ 188] = 'GF'
        self.columnNameList[ 189] = 'GG'
        self.columnNameList[ 190] = 'GH'
        self.columnNameList[ 191] = 'GI'
        self.columnNameList[ 192] = 'GJ'
        self.columnNameList[ 193] = 'GK'
        self.columnNameList[ 194] = 'GL'
        self.columnNameList[ 195] = 'GM'
        self.columnNameList[ 196] = 'GN'
        self.columnNameList[ 197] = 'GO'
        self.columnNameList[ 198] = 'GP'
        self.columnNameList[ 199] = 'GQ'
        self.columnNameList[ 200] = 'GR'
        self.columnNameList[ 201] = 'GS'
        self.columnNameList[ 202] = 'GT'
        self.columnNameList[ 203] = 'GU'
        self.columnNameList[ 204] = 'GV'
        self.columnNameList[ 205] = 'GW'
        self.columnNameList[ 206] = 'GX'
        self.columnNameList[ 207] = 'GY'
        self.columnNameList[ 208] = 'GZ'
        self.columnNameList[ 209] = 'HA'
        self.columnNameList[ 210] = 'HB'
        self.columnNameList[ 211] = 'HC'
        self.columnNameList[ 212] = 'HD'
        self.columnNameList[ 213] = 'HE'
        self.columnNameList[ 214] = 'HF'
        self.columnNameList[ 215] = 'HG'
        self.columnNameList[ 216] = 'HH'
        self.columnNameList[ 217] = 'HI'
        self.columnNameList[ 218] = 'HJ'
        self.columnNameList[ 219] = 'HK'
        self.columnNameList[ 220] = 'HL'
        self.columnNameList[ 221] = 'HM'
        self.columnNameList[ 222] = 'HN'
        self.columnNameList[ 223] = 'HO'
        self.columnNameList[ 224] = 'HP'
        self.columnNameList[ 225] = 'HQ'
        self.columnNameList[ 226] = 'HR'
        self.columnNameList[ 227] = 'HS'
        self.columnNameList[ 228] = 'HT'
        self.columnNameList[ 229] = 'HU'
        self.columnNameList[ 230] = 'HV'
        self.columnNameList[ 231] = 'HW'
        self.columnNameList[ 232] = 'HX'
        self.columnNameList[ 233] = 'HY'
        self.columnNameList[ 234] = 'HZ'
        self.columnNameList[ 235] = 'IA'
        self.columnNameList[ 236] = 'IB'
        self.columnNameList[ 237] = 'IC'
        self.columnNameList[ 238] = 'ID'
        self.columnNameList[ 239] = 'IE'
        self.columnNameList[ 240] = 'IF'
        self.columnNameList[ 241] = 'IG'
        self.columnNameList[ 242] = 'IH'
        self.columnNameList[ 243] = 'II'
        self.columnNameList[ 244] = 'IJ'
        self.columnNameList[ 245] = 'IK'
        self.columnNameList[ 246] = 'IL'
        self.columnNameList[ 247] = 'IM'
        self.columnNameList[ 248] = 'IN'
        self.columnNameList[ 249] = 'IO'
        self.columnNameList[ 250] = 'IP'
        self.columnNameList[ 251] = 'IQ'
        self.columnNameList[ 252] = 'IR'
        self.columnNameList[ 253] = 'IS'
        self.columnNameList[ 254] = 'IT'
        self.columnNameList[ 255] = 'IU'
        self.columnNameList[ 256] = 'IV'
        self.columnNameList[ 257] = 'IW'
        self.columnNameList[ 258] = 'IX'
        self.columnNameList[ 259] = 'IY'
        self.columnNameList[ 260] = 'IZ'
        self.columnNameList[ 261] = 'JA'
        self.columnNameList[ 262] = 'JB'
        self.columnNameList[ 263] = 'JC'
        self.columnNameList[ 264] = 'JD'
        self.columnNameList[ 265] = 'JE'
        self.columnNameList[ 266] = 'JF'
        self.columnNameList[ 267] = 'JG'
        self.columnNameList[ 268] = 'JH'
        self.columnNameList[ 269] = 'JI'
        self.columnNameList[ 270] = 'JJ'
        self.columnNameList[ 271] = 'JK'
        self.columnNameList[ 272] = 'JL'
        self.columnNameList[ 273] = 'JM'
        self.columnNameList[ 274] = 'JN'
        self.columnNameList[ 275] = 'JO'
        self.columnNameList[ 276] = 'JP'
        self.columnNameList[ 277] = 'JQ'
        self.columnNameList[ 278] = 'JR'
        self.columnNameList[ 279] = 'JS'
        self.columnNameList[ 280] = 'JT'
        self.columnNameList[ 281] = 'JU'
        self.columnNameList[ 282] = 'JV'
        self.columnNameList[ 283] = 'JW'
        self.columnNameList[ 284] = 'JX'
        self.columnNameList[ 285] = 'JY'
        self.columnNameList[ 286] = 'JZ'
        self.columnNameList[ 287] = 'KA'
        self.columnNameList[ 288] = 'KB'
        self.columnNameList[ 289] = 'KC'
        self.columnNameList[ 290] = 'KD'
        self.columnNameList[ 291] = 'KE'
        self.columnNameList[ 292] = 'KF'
        self.columnNameList[ 293] = 'KG'
        self.columnNameList[ 294] = 'KH'
        self.columnNameList[ 295] = 'KI'
        self.columnNameList[ 296] = 'KJ'
        self.columnNameList[ 297] = 'KK'
        self.columnNameList[ 298] = 'KL'
        self.columnNameList[ 299] = 'KM'
        self.columnNameList[ 300] = 'KN'
        self.columnNameList[ 301] = 'KO'
        self.columnNameList[ 302] = 'KP'
        self.columnNameList[ 303] = 'KQ'
        self.columnNameList[ 304] = 'KR'
        self.columnNameList[ 305] = 'KS'
        self.columnNameList[ 306] = 'KT'
        self.columnNameList[ 307] = 'KU'
        self.columnNameList[ 308] = 'KV'
        self.columnNameList[ 309] = 'KW'
        self.columnNameList[ 310] = 'KX'
        self.columnNameList[ 311] = 'KY'
        self.columnNameList[ 312] = 'KZ'
        self.columnNameList[ 313] = 'LA'
        self.columnNameList[ 314] = 'LB'
        self.columnNameList[ 315] = 'LC'
        self.columnNameList[ 316] = 'LD'
        self.columnNameList[ 317] = 'LE'
        self.columnNameList[ 318] = 'LF'
        self.columnNameList[ 319] = 'LG'
        self.columnNameList[ 320] = 'LH'
        self.columnNameList[ 321] = 'LI'
        self.columnNameList[ 322] = 'LJ'
        self.columnNameList[ 323] = 'LK'
        self.columnNameList[ 324] = 'LL'
        self.columnNameList[ 325] = 'LM'
        self.columnNameList[ 326] = 'LN'
        self.columnNameList[ 327] = 'LO'
        self.columnNameList[ 328] = 'LP'
        self.columnNameList[ 329] = 'LQ'
        self.columnNameList[ 330] = 'LR'
        self.columnNameList[ 331] = 'LS'
        self.columnNameList[ 332] = 'LT'
        self.columnNameList[ 333] = 'LU'
        self.columnNameList[ 334] = 'LV'
        self.columnNameList[ 335] = 'LW'
        self.columnNameList[ 336] = 'LX'
        self.columnNameList[ 337] = 'LY'
        self.columnNameList[ 338] = 'LZ'
        self.columnNameList[ 339] = 'MA'
        self.columnNameList[ 340] = 'MB'
        self.columnNameList[ 341] = 'MC'
        self.columnNameList[ 342] = 'MD'
        self.columnNameList[ 343] = 'ME'
        self.columnNameList[ 344] = 'MF'
        self.columnNameList[ 345] = 'MG'
        self.columnNameList[ 346] = 'MH'
        self.columnNameList[ 347] = 'MI'
        self.columnNameList[ 348] = 'MJ'
        self.columnNameList[ 349] = 'MK'
        self.columnNameList[ 350] = 'ML'
        self.columnNameList[ 351] = 'MM'
        self.columnNameList[ 352] = 'MN'
        self.columnNameList[ 353] = 'MO'
        self.columnNameList[ 354] = 'MP'
        self.columnNameList[ 355] = 'MQ'
        self.columnNameList[ 356] = 'MR'
        self.columnNameList[ 357] = 'MS'
        self.columnNameList[ 358] = 'MT'
        self.columnNameList[ 359] = 'MU'
        self.columnNameList[ 360] = 'MV'
        self.columnNameList[ 361] = 'MW'
        self.columnNameList[ 362] = 'MX'
        self.columnNameList[ 363] = 'MY'
        self.columnNameList[ 364] = 'MZ'
        self.columnNameList[ 365] = 'NA'
        self.columnNameList[ 366] = 'NB'
        self.columnNameList[ 367] = 'NC'
        self.columnNameList[ 368] = 'ND'
        self.columnNameList[ 369] = 'NE'
        self.columnNameList[ 370] = 'NF'
        self.columnNameList[ 371] = 'NG'
        self.columnNameList[ 372] = 'NH'
        self.columnNameList[ 373] = 'NI'
        self.columnNameList[ 374] = 'NJ'
        self.columnNameList[ 375] = 'NK'
        self.columnNameList[ 376] = 'NL'
        self.columnNameList[ 377] = 'NM'
        self.columnNameList[ 378] = 'NN'
        self.columnNameList[ 379] = 'NO'
        self.columnNameList[ 380] = 'NP'
        self.columnNameList[ 381] = 'NQ'
        self.columnNameList[ 382] = 'NR'
        self.columnNameList[ 383] = 'NS'
        self.columnNameList[ 384] = 'NT'
        self.columnNameList[ 385] = 'NU'
        self.columnNameList[ 386] = 'NV'
        self.columnNameList[ 387] = 'NW'
        self.columnNameList[ 388] = 'NX'
        self.columnNameList[ 389] = 'NY'
        self.columnNameList[ 390] = 'NZ'
        self.columnNameList[ 391] = 'OA'
        self.columnNameList[ 392] = 'OB'
        self.columnNameList[ 393] = 'OC'
        self.columnNameList[ 394] = 'OD'
        self.columnNameList[ 395] = 'OE'
        self.columnNameList[ 396] = 'OF'
        self.columnNameList[ 397] = 'OG'
        self.columnNameList[ 398] = 'OH'
        self.columnNameList[ 399] = 'OI'
        self.columnNameList[ 400] = 'OJ'
        self.columnNameList[ 401] = 'OK'
        self.columnNameList[ 402] = 'OL'
        self.columnNameList[ 403] = 'OM'
        self.columnNameList[ 404] = 'ON'
        self.columnNameList[ 405] = 'OO'
        self.columnNameList[ 406] = 'OP'
        self.columnNameList[ 407] = 'OQ'
        self.columnNameList[ 408] = 'OR'
        self.columnNameList[ 409] = 'OS'
        self.columnNameList[ 410] = 'OT'
        self.columnNameList[ 411] = 'OU'
        self.columnNameList[ 412] = 'OV'
        self.columnNameList[ 413] = 'OW'
        self.columnNameList[ 414] = 'OX'
        self.columnNameList[ 415] = 'OY'
        self.columnNameList[ 416] = 'OZ'
        self.columnNameList[ 417] = 'PA'
        self.columnNameList[ 418] = 'PB'
        self.columnNameList[ 419] = 'PC'
        self.columnNameList[ 420] = 'PD'
        self.columnNameList[ 421] = 'PE'
        self.columnNameList[ 422] = 'PF'
        self.columnNameList[ 423] = 'PG'
        self.columnNameList[ 424] = 'PH'
        self.columnNameList[ 425] = 'PI'
        self.columnNameList[ 426] = 'PJ'
        self.columnNameList[ 427] = 'PK'
        self.columnNameList[ 428] = 'PL'
        self.columnNameList[ 429] = 'PM'
        self.columnNameList[ 430] = 'PN'
        self.columnNameList[ 431] = 'PO'
        self.columnNameList[ 432] = 'PP'
        self.columnNameList[ 433] = 'PQ'
        self.columnNameList[ 434] = 'PR'
        self.columnNameList[ 435] = 'PS'
        self.columnNameList[ 436] = 'PT'
        self.columnNameList[ 437] = 'PU'
        self.columnNameList[ 438] = 'PV'
        self.columnNameList[ 439] = 'PW'
        self.columnNameList[ 440] = 'PX'
        self.columnNameList[ 441] = 'PY'
        self.columnNameList[ 442] = 'PZ'
        self.columnNameList[ 443] = 'QA'
        self.columnNameList[ 444] = 'QB'
        self.columnNameList[ 445] = 'QC'
        self.columnNameList[ 446] = 'QD'
        self.columnNameList[ 447] = 'QE'
        self.columnNameList[ 448] = 'QF'
        self.columnNameList[ 449] = 'QG'
        self.columnNameList[ 450] = 'QH'
        self.columnNameList[ 451] = 'QI'
        self.columnNameList[ 452] = 'QJ'
        self.columnNameList[ 453] = 'QK'
        self.columnNameList[ 454] = 'QL'
        self.columnNameList[ 455] = 'QM'
        self.columnNameList[ 456] = 'QN'
        self.columnNameList[ 457] = 'QO'
        self.columnNameList[ 458] = 'QP'
        self.columnNameList[ 459] = 'QQ'
        self.columnNameList[ 460] = 'QR'
        self.columnNameList[ 461] = 'QS'
        self.columnNameList[ 462] = 'QT'
        self.columnNameList[ 463] = 'QU'
        self.columnNameList[ 464] = 'QV'
        self.columnNameList[ 465] = 'QW'
        self.columnNameList[ 466] = 'QX'
        self.columnNameList[ 467] = 'QY'
        self.columnNameList[ 468] = 'QZ'
        self.columnNameList[ 469] = 'RA'
        self.columnNameList[ 470] = 'RB'
        self.columnNameList[ 471] = 'RC'
        self.columnNameList[ 472] = 'RD'
        self.columnNameList[ 473] = 'RE'
        self.columnNameList[ 474] = 'RF'
        self.columnNameList[ 475] = 'RG'
        self.columnNameList[ 476] = 'RH'
        self.columnNameList[ 477] = 'RI'
        self.columnNameList[ 478] = 'RJ'
        self.columnNameList[ 479] = 'RK'
        self.columnNameList[ 480] = 'RL'
        self.columnNameList[ 481] = 'RM'
        self.columnNameList[ 482] = 'RN'
        self.columnNameList[ 483] = 'RO'
        self.columnNameList[ 484] = 'RP'
        self.columnNameList[ 485] = 'RQ'
        self.columnNameList[ 486] = 'RR'
        self.columnNameList[ 487] = 'RS'
        self.columnNameList[ 488] = 'RT'
        self.columnNameList[ 489] = 'RU'
        self.columnNameList[ 490] = 'RV'
        self.columnNameList[ 491] = 'RW'
        self.columnNameList[ 492] = 'RX'
        self.columnNameList[ 493] = 'RY'
        self.columnNameList[ 494] = 'RZ'
        self.columnNameList[ 495] = 'SA'
        self.columnNameList[ 496] = 'SB'
        self.columnNameList[ 497] = 'SC'
        self.columnNameList[ 498] = 'SD'
        self.columnNameList[ 499] = 'SE'
        self.columnNameList[ 500] = 'SF'
        self.columnNameList[ 501] = 'SG'
        self.columnNameList[ 502] = 'SH'
        self.columnNameList[ 503] = 'SI'
        self.columnNameList[ 504] = 'SJ'
        self.columnNameList[ 505] = 'SK'
        self.columnNameList[ 506] = 'SL'
        self.columnNameList[ 507] = 'SM'
        self.columnNameList[ 508] = 'SN'
        self.columnNameList[ 509] = 'SO'
        self.columnNameList[ 510] = 'SP'
        self.columnNameList[ 511] = 'SQ'
        self.columnNameList[ 512] = 'SR'
        self.columnNameList[ 513] = 'SS'
        self.columnNameList[ 514] = 'ST'
        self.columnNameList[ 515] = 'SU'
        self.columnNameList[ 516] = 'SV'
        self.columnNameList[ 517] = 'SW'
        self.columnNameList[ 518] = 'SX'
        self.columnNameList[ 519] = 'SY'
        self.columnNameList[ 520] = 'SZ'
        self.columnNameList[ 521] = 'TA'
        self.columnNameList[ 522] = 'TB'
        self.columnNameList[ 523] = 'TC'
        self.columnNameList[ 524] = 'TD'
        self.columnNameList[ 525] = 'TE'
        self.columnNameList[ 526] = 'TF'
        self.columnNameList[ 527] = 'TG'
        self.columnNameList[ 528] = 'TH'
        self.columnNameList[ 529] = 'TI'
        self.columnNameList[ 530] = 'TJ'
        self.columnNameList[ 531] = 'TK'
        self.columnNameList[ 532] = 'TL'
        self.columnNameList[ 533] = 'TM'
        self.columnNameList[ 534] = 'TN'
        self.columnNameList[ 535] = 'TO'
        self.columnNameList[ 536] = 'TP'
        self.columnNameList[ 537] = 'TQ'
        self.columnNameList[ 538] = 'TR'
        self.columnNameList[ 539] = 'TS'
        self.columnNameList[ 540] = 'TT'
        self.columnNameList[ 541] = 'TU'
        self.columnNameList[ 542] = 'TV'
        self.columnNameList[ 543] = 'TW'
        self.columnNameList[ 544] = 'TX'
        self.columnNameList[ 545] = 'TY'
        self.columnNameList[ 546] = 'TZ'
        self.columnNameList[ 547] = 'UA'
        self.columnNameList[ 548] = 'UB'
        self.columnNameList[ 549] = 'UC'
        self.columnNameList[ 550] = 'UD'
        self.columnNameList[ 551] = 'UE'
        self.columnNameList[ 552] = 'UF'
        self.columnNameList[ 553] = 'UG'
        self.columnNameList[ 554] = 'UH'
        self.columnNameList[ 555] = 'UI'
        self.columnNameList[ 556] = 'UJ'
        self.columnNameList[ 557] = 'UK'
        self.columnNameList[ 558] = 'UL'
        self.columnNameList[ 559] = 'UM'
        self.columnNameList[ 560] = 'UN'
        self.columnNameList[ 561] = 'UO'
        self.columnNameList[ 562] = 'UP'
        self.columnNameList[ 563] = 'UQ'
        self.columnNameList[ 564] = 'UR'
        self.columnNameList[ 565] = 'US'
        self.columnNameList[ 566] = 'UT'
        self.columnNameList[ 567] = 'UU'
        self.columnNameList[ 568] = 'UV'
        self.columnNameList[ 569] = 'UW'
        self.columnNameList[ 570] = 'UX'
        self.columnNameList[ 571] = 'UY'
        self.columnNameList[ 572] = 'UZ'
        self.columnNameList[ 573] = 'VA'
        self.columnNameList[ 574] = 'VB'
        self.columnNameList[ 575] = 'VC'
        self.columnNameList[ 576] = 'VD'
        self.columnNameList[ 577] = 'VE'
        self.columnNameList[ 578] = 'VF'
        self.columnNameList[ 579] = 'VG'
        self.columnNameList[ 580] = 'VH'
        self.columnNameList[ 581] = 'VI'
        self.columnNameList[ 582] = 'VJ'
        self.columnNameList[ 583] = 'VK'
        self.columnNameList[ 584] = 'VL'
        self.columnNameList[ 585] = 'VM'
        self.columnNameList[ 586] = 'VN'
        self.columnNameList[ 587] = 'VO'
        self.columnNameList[ 588] = 'VP'
        self.columnNameList[ 589] = 'VQ'
        self.columnNameList[ 590] = 'VR'
        self.columnNameList[ 591] = 'VS'
        self.columnNameList[ 592] = 'VT'
        self.columnNameList[ 593] = 'VU'
        self.columnNameList[ 594] = 'VV'
        self.columnNameList[ 595] = 'VW'
        self.columnNameList[ 596] = 'VX'
        self.columnNameList[ 597] = 'VY'
        self.columnNameList[ 598] = 'VZ'
        self.columnNameList[ 599] = 'WA'
        self.columnNameList[ 600] = 'WB'
        self.columnNameList[ 601] = 'WC'
        self.columnNameList[ 602] = 'WD'
        self.columnNameList[ 603] = 'WE'
        self.columnNameList[ 604] = 'WF'
        self.columnNameList[ 605] = 'WG'
        self.columnNameList[ 606] = 'WH'
        self.columnNameList[ 607] = 'WI'
        self.columnNameList[ 608] = 'WJ'
        self.columnNameList[ 609] = 'WK'
        self.columnNameList[ 610] = 'WL'
        self.columnNameList[ 611] = 'WM'
        self.columnNameList[ 612] = 'WN'
        self.columnNameList[ 613] = 'WO'
        self.columnNameList[ 614] = 'WP'
        self.columnNameList[ 615] = 'WQ'
        self.columnNameList[ 616] = 'WR'
        self.columnNameList[ 617] = 'WS'
        self.columnNameList[ 618] = 'WT'
        self.columnNameList[ 619] = 'WU'
        self.columnNameList[ 620] = 'WV'
        self.columnNameList[ 621] = 'WW'
        self.columnNameList[ 622] = 'WX'
        self.columnNameList[ 623] = 'WY'
        self.columnNameList[ 624] = 'WZ'
        self.columnNameList[ 625] = 'XA'
        self.columnNameList[ 626] = 'XB'
        self.columnNameList[ 627] = 'XC'
        self.columnNameList[ 628] = 'XD'
        self.columnNameList[ 629] = 'XE'
        self.columnNameList[ 630] = 'XF'
        self.columnNameList[ 631] = 'XG'
        self.columnNameList[ 632] = 'XH'
        self.columnNameList[ 633] = 'XI'
        self.columnNameList[ 634] = 'XJ'
        self.columnNameList[ 635] = 'XK'
        self.columnNameList[ 636] = 'XL'
        self.columnNameList[ 637] = 'XM'
        self.columnNameList[ 638] = 'XN'
        self.columnNameList[ 639] = 'XO'
        self.columnNameList[ 640] = 'XP'
        self.columnNameList[ 641] = 'XQ'
        self.columnNameList[ 642] = 'XR'
        self.columnNameList[ 643] = 'XS'
        self.columnNameList[ 644] = 'XT'
        self.columnNameList[ 645] = 'XU'
        self.columnNameList[ 646] = 'XV'
        self.columnNameList[ 647] = 'XW'
        self.columnNameList[ 648] = 'XX'
        self.columnNameList[ 649] = 'XY'
        self.columnNameList[ 650] = 'XZ'
        self.columnNameList[ 651] = 'YA'
        self.columnNameList[ 652] = 'YB'
        self.columnNameList[ 653] = 'YC'
        self.columnNameList[ 654] = 'YD'
        self.columnNameList[ 655] = 'YE'
        self.columnNameList[ 656] = 'YF'
        self.columnNameList[ 657] = 'YG'
        self.columnNameList[ 658] = 'YH'
        self.columnNameList[ 659] = 'YI'
        self.columnNameList[ 660] = 'YJ'
        self.columnNameList[ 661] = 'YK'
        self.columnNameList[ 662] = 'YL'
        self.columnNameList[ 663] = 'YM'
        self.columnNameList[ 664] = 'YN'
        self.columnNameList[ 665] = 'YO'
        self.columnNameList[ 666] = 'YP'
        self.columnNameList[ 667] = 'YQ'
        self.columnNameList[ 668] = 'YR'
        self.columnNameList[ 669] = 'YS'
        self.columnNameList[ 670] = 'YT'
        self.columnNameList[ 671] = 'YU'
        self.columnNameList[ 672] = 'YV'
        self.columnNameList[ 673] = 'YW'
        self.columnNameList[ 674] = 'YX'
        self.columnNameList[ 675] = 'YY'
        self.columnNameList[ 676] = 'YZ'
        self.columnNameList[ 677] = 'ZA'
        self.columnNameList[ 678] = 'ZB'
        self.columnNameList[ 679] = 'ZC'
        self.columnNameList[ 680] = 'ZD'
        self.columnNameList[ 681] = 'ZE'
        self.columnNameList[ 682] = 'ZF'
        self.columnNameList[ 683] = 'ZG'
        self.columnNameList[ 684] = 'ZH'
        self.columnNameList[ 685] = 'ZI'
        self.columnNameList[ 686] = 'ZJ'
        self.columnNameList[ 687] = 'ZK'
        self.columnNameList[ 688] = 'ZL'
        self.columnNameList[ 689] = 'ZM'
        self.columnNameList[ 690] = 'ZN'
        self.columnNameList[ 691] = 'ZO'
        self.columnNameList[ 692] = 'ZP'
        self.columnNameList[ 693] = 'ZQ'
        self.columnNameList[ 694] = 'ZR'
        self.columnNameList[ 695] = 'ZS'
        self.columnNameList[ 696] = 'ZT'
        self.columnNameList[ 697] = 'ZU'
        self.columnNameList[ 698] = 'ZV'
        self.columnNameList[ 699] = 'ZW'
        self.columnNameList[ 700] = 'ZX'
        self.columnNameList[ 701] = 'ZY'
        self.columnNameList[ 702] = 'ZZ'
        self.columnNameList[ 703] = 'AAA'
        self.columnNameList[ 704] = 'AAB'
        self.columnNameList[ 705] = 'AAC'
        self.columnNameList[ 706] = 'AAD'
        self.columnNameList[ 707] = 'AAE'
        self.columnNameList[ 708] = 'AAF'
        self.columnNameList[ 709] = 'AAG'
        self.columnNameList[ 710] = 'AAH'
        self.columnNameList[ 711] = 'AAI'
        self.columnNameList[ 712] = 'AAJ'
        self.columnNameList[ 713] = 'AAK'
        self.columnNameList[ 714] = 'AAL'
        self.columnNameList[ 715] = 'AAM'
        self.columnNameList[ 716] = 'AAN'
        self.columnNameList[ 717] = 'AAO'
        self.columnNameList[ 718] = 'AAP'
        self.columnNameList[ 719] = 'AAQ'
        self.columnNameList[ 720] = 'AAR'
        self.columnNameList[ 721] = 'AAS'
        self.columnNameList[ 722] = 'AAT'
        self.columnNameList[ 723] = 'AAU'
        self.columnNameList[ 724] = 'AAV'
        self.columnNameList[ 725] = 'AAW'
        self.columnNameList[ 726] = 'AAX'
        self.columnNameList[ 727] = 'AAY'
        self.columnNameList[ 728] = 'AAZ'
        self.columnNameList[ 729] = 'ABA'
        self.columnNameList[ 730] = 'ABB'
        self.columnNameList[ 731] = 'ABC'
        self.columnNameList[ 732] = 'ABD'
        self.columnNameList[ 733] = 'ABE'
        self.columnNameList[ 734] = 'ABF'
        self.columnNameList[ 735] = 'ABG'
        self.columnNameList[ 736] = 'ABH'
        self.columnNameList[ 737] = 'ABI'
        self.columnNameList[ 738] = 'ABJ'
        self.columnNameList[ 739] = 'ABK'
        self.columnNameList[ 740] = 'ABL'
        self.columnNameList[ 741] = 'ABM'
        self.columnNameList[ 742] = 'ABN'
        self.columnNameList[ 743] = 'ABO'
        self.columnNameList[ 744] = 'ABP'
        self.columnNameList[ 745] = 'ABQ'
        self.columnNameList[ 746] = 'ABR'
        self.columnNameList[ 747] = 'ABS'
        self.columnNameList[ 748] = 'ABT'
        self.columnNameList[ 749] = 'ABU'
        self.columnNameList[ 750] = 'ABV'
        self.columnNameList[ 751] = 'ABW'
        self.columnNameList[ 752] = 'ABX'
        self.columnNameList[ 753] = 'ABY'
        self.columnNameList[ 754] = 'ABZ'
        self.columnNameList[ 755] = 'ACA'
        self.columnNameList[ 756] = 'ACB'
        self.columnNameList[ 757] = 'ACC'
        self.columnNameList[ 758] = 'ACD'
        self.columnNameList[ 759] = 'ACE'
        self.columnNameList[ 760] = 'ACF'
        self.columnNameList[ 761] = 'ACG'
        self.columnNameList[ 762] = 'ACH'
        self.columnNameList[ 763] = 'ACI'
        self.columnNameList[ 764] = 'ACJ'
        self.columnNameList[ 765] = 'ACK'
        self.columnNameList[ 766] = 'ACL'
        self.columnNameList[ 767] = 'ACM'
        self.columnNameList[ 768] = 'ACN'
        self.columnNameList[ 769] = 'ACO'
        self.columnNameList[ 770] = 'ACP'
        self.columnNameList[ 771] = 'ACQ'
        self.columnNameList[ 772] = 'ACR'
        self.columnNameList[ 773] = 'ACS'
        self.columnNameList[ 774] = 'ACT'
        self.columnNameList[ 775] = 'ACU'
        self.columnNameList[ 776] = 'ACV'
        self.columnNameList[ 777] = 'ACW'
        self.columnNameList[ 778] = 'ACX'
        self.columnNameList[ 779] = 'ACY'
        self.columnNameList[ 780] = 'ACZ'
        self.columnNameList[ 781] = 'ADA'
        self.columnNameList[ 782] = 'ADB'
        self.columnNameList[ 783] = 'ADC'
        self.columnNameList[ 784] = 'ADD'
        self.columnNameList[ 785] = 'ADE'
        self.columnNameList[ 786] = 'ADF'
        self.columnNameList[ 787] = 'ADG'
        self.columnNameList[ 788] = 'ADH'
        self.columnNameList[ 789] = 'ADI'
        self.columnNameList[ 790] = 'ADJ'
        self.columnNameList[ 791] = 'ADK'
        self.columnNameList[ 792] = 'ADL'
        self.columnNameList[ 793] = 'ADM'
        self.columnNameList[ 794] = 'ADN'
        self.columnNameList[ 795] = 'ADO'
        self.columnNameList[ 796] = 'ADP'
        self.columnNameList[ 797] = 'ADQ'
        self.columnNameList[ 798] = 'ADR'
        self.columnNameList[ 799] = 'ADS'
        self.columnNameList[ 800] = 'ADT'
        self.columnNameList[ 801] = 'ADU'
        self.columnNameList[ 802] = 'ADV'
        self.columnNameList[ 803] = 'ADW'
        self.columnNameList[ 804] = 'ADX'
        self.columnNameList[ 805] = 'ADY'
        self.columnNameList[ 806] = 'ADZ'
        self.columnNameList[ 807] = 'AEA'
        self.columnNameList[ 808] = 'AEB'
        self.columnNameList[ 809] = 'AEC'
        self.columnNameList[ 810] = 'AED'
        self.columnNameList[ 811] = 'AEE'
        self.columnNameList[ 812] = 'AEF'
        self.columnNameList[ 813] = 'AEG'
        self.columnNameList[ 814] = 'AEH'
        self.columnNameList[ 815] = 'AEI'
        self.columnNameList[ 816] = 'AEJ'
        self.columnNameList[ 817] = 'AEK'
        self.columnNameList[ 818] = 'AEL'
        self.columnNameList[ 819] = 'AEM'
        self.columnNameList[ 820] = 'AEN'
        self.columnNameList[ 821] = 'AEO'
        self.columnNameList[ 822] = 'AEP'
        self.columnNameList[ 823] = 'AEQ'
        self.columnNameList[ 824] = 'AER'
        self.columnNameList[ 825] = 'AES'
        self.columnNameList[ 826] = 'AET'
        self.columnNameList[ 827] = 'AEU'
        self.columnNameList[ 828] = 'AEV'
        self.columnNameList[ 829] = 'AEW'
        self.columnNameList[ 830] = 'AEX'
        self.columnNameList[ 831] = 'AEY'
        self.columnNameList[ 832] = 'AEZ'
        self.columnNameList[ 833] = 'AFA'
        self.columnNameList[ 834] = 'AFB'
        self.columnNameList[ 835] = 'AFC'
        self.columnNameList[ 836] = 'AFD'
        self.columnNameList[ 837] = 'AFE'
        self.columnNameList[ 838] = 'AFF'
        self.columnNameList[ 839] = 'AFG'
        self.columnNameList[ 840] = 'AFH'
        self.columnNameList[ 841] = 'AFI'
        self.columnNameList[ 842] = 'AFJ'
        self.columnNameList[ 843] = 'AFK'
        self.columnNameList[ 844] = 'AFL'
        self.columnNameList[ 845] = 'AFM'
        self.columnNameList[ 846] = 'AFN'
        self.columnNameList[ 847] = 'AFO'
        self.columnNameList[ 848] = 'AFP'
        self.columnNameList[ 849] = 'AFQ'
        self.columnNameList[ 850] = 'AFR'
        self.columnNameList[ 851] = 'AFS'
        self.columnNameList[ 852] = 'AFT'
        self.columnNameList[ 853] = 'AFU'
        self.columnNameList[ 854] = 'AFV'
        self.columnNameList[ 855] = 'AFW'
        self.columnNameList[ 856] = 'AFX'
        self.columnNameList[ 857] = 'AFY'
        self.columnNameList[ 858] = 'AFZ'
        self.columnNameList[ 859] = 'AGA'
        self.columnNameList[ 860] = 'AGB'
        self.columnNameList[ 861] = 'AGC'
        self.columnNameList[ 862] = 'AGD'
        self.columnNameList[ 863] = 'AGE'
        self.columnNameList[ 864] = 'AGF'
        self.columnNameList[ 865] = 'AGG'
        self.columnNameList[ 866] = 'AGH'
        self.columnNameList[ 867] = 'AGI'
        self.columnNameList[ 868] = 'AGJ'
        self.columnNameList[ 869] = 'AGK'
        self.columnNameList[ 870] = 'AGL'
        self.columnNameList[ 871] = 'AGM'
        self.columnNameList[ 872] = 'AGN'
        self.columnNameList[ 873] = 'AGO'
        self.columnNameList[ 874] = 'AGP'
        self.columnNameList[ 875] = 'AGQ'
        self.columnNameList[ 876] = 'AGR'
        self.columnNameList[ 877] = 'AGS'
        self.columnNameList[ 878] = 'AGT'
        self.columnNameList[ 879] = 'AGU'
        self.columnNameList[ 880] = 'AGV'
        self.columnNameList[ 881] = 'AGW'
        self.columnNameList[ 882] = 'AGX'
        self.columnNameList[ 883] = 'AGY'
        self.columnNameList[ 884] = 'AGZ'
        self.columnNameList[ 885] = 'AHA'
        self.columnNameList[ 886] = 'AHB'
        self.columnNameList[ 887] = 'AHC'
        self.columnNameList[ 888] = 'AHD'
        self.columnNameList[ 889] = 'AHE'
        self.columnNameList[ 890] = 'AHF'
        self.columnNameList[ 891] = 'AHG'
        self.columnNameList[ 892] = 'AHH'
        self.columnNameList[ 893] = 'AHI'
        self.columnNameList[ 894] = 'AHJ'
        self.columnNameList[ 895] = 'AHK'
        self.columnNameList[ 896] = 'AHL'
        self.columnNameList[ 897] = 'AHM'
        self.columnNameList[ 898] = 'AHN'
        self.columnNameList[ 899] = 'AHO'
        self.columnNameList[ 900] = 'AHP'
        self.columnNameList[ 901] = 'AHQ'
        self.columnNameList[ 902] = 'AHR'
        self.columnNameList[ 903] = 'AHS'
        self.columnNameList[ 904] = 'AHT'
        self.columnNameList[ 905] = 'AHU'
        self.columnNameList[ 906] = 'AHV'
        self.columnNameList[ 907] = 'AHW'
        self.columnNameList[ 908] = 'AHX'
        self.columnNameList[ 909] = 'AHY'
        self.columnNameList[ 910] = 'AHZ'
        self.columnNameList[ 911] = 'AIA'
        self.columnNameList[ 912] = 'AIB'
        self.columnNameList[ 913] = 'AIC'
        self.columnNameList[ 914] = 'AID'
        self.columnNameList[ 915] = 'AIE'
        self.columnNameList[ 916] = 'AIF'
        self.columnNameList[ 917] = 'AIG'
        self.columnNameList[ 918] = 'AIH'
        self.columnNameList[ 919] = 'AII'
        self.columnNameList[ 920] = 'AIJ'
        self.columnNameList[ 921] = 'AIK'
        self.columnNameList[ 922] = 'AIL'
        self.columnNameList[ 923] = 'AIM'
        self.columnNameList[ 924] = 'AIN'
        self.columnNameList[ 925] = 'AIO'
        self.columnNameList[ 926] = 'AIP'
        self.columnNameList[ 927] = 'AIQ'
        self.columnNameList[ 928] = 'AIR'
        self.columnNameList[ 929] = 'AIS'
        self.columnNameList[ 930] = 'AIT'
        self.columnNameList[ 931] = 'AIU'
        self.columnNameList[ 932] = 'AIV'
        self.columnNameList[ 933] = 'AIW'
        self.columnNameList[ 934] = 'AIX'
        self.columnNameList[ 935] = 'AIY'
        self.columnNameList[ 936] = 'AIZ'
        self.columnNameList[ 937] = 'AJA'
        self.columnNameList[ 938] = 'AJB'
        self.columnNameList[ 939] = 'AJC'
        self.columnNameList[ 940] = 'AJD'
        self.columnNameList[ 941] = 'AJE'
        self.columnNameList[ 942] = 'AJF'
        self.columnNameList[ 943] = 'AJG'
        self.columnNameList[ 944] = 'AJH'
        self.columnNameList[ 945] = 'AJI'
        self.columnNameList[ 946] = 'AJJ'
        self.columnNameList[ 947] = 'AJK'
        self.columnNameList[ 948] = 'AJL'
        self.columnNameList[ 949] = 'AJM'
        self.columnNameList[ 950] = 'AJN'
        self.columnNameList[ 951] = 'AJO'
        self.columnNameList[ 952] = 'AJP'
        self.columnNameList[ 953] = 'AJQ'
        self.columnNameList[ 954] = 'AJR'
        self.columnNameList[ 955] = 'AJS'
        self.columnNameList[ 956] = 'AJT'
        self.columnNameList[ 957] = 'AJU'
        self.columnNameList[ 958] = 'AJV'
        self.columnNameList[ 959] = 'AJW'
        self.columnNameList[ 960] = 'AJX'
        self.columnNameList[ 961] = 'AJY'
        self.columnNameList[ 962] = 'AJZ'
        self.columnNameList[ 963] = 'AKA'
        self.columnNameList[ 964] = 'AKB'
        self.columnNameList[ 965] = 'AKC'
        self.columnNameList[ 966] = 'AKD'
        self.columnNameList[ 967] = 'AKE'
        self.columnNameList[ 968] = 'AKF'
        self.columnNameList[ 969] = 'AKG'
        self.columnNameList[ 970] = 'AKH'
        self.columnNameList[ 971] = 'AKI'
        self.columnNameList[ 972] = 'AKJ'
        self.columnNameList[ 973] = 'AKK'
        self.columnNameList[ 974] = 'AKL'
        self.columnNameList[ 975] = 'AKM'
        self.columnNameList[ 976] = 'AKN'
        self.columnNameList[ 977] = 'AKO'
        self.columnNameList[ 978] = 'AKP'
        self.columnNameList[ 979] = 'AKQ'
        self.columnNameList[ 980] = 'AKR'
        self.columnNameList[ 981] = 'AKS'
        self.columnNameList[ 982] = 'AKT'
        self.columnNameList[ 983] = 'AKU'
        self.columnNameList[ 984] = 'AKV'
        self.columnNameList[ 985] = 'AKW'
        self.columnNameList[ 986] = 'AKX'
        self.columnNameList[ 987] = 'AKY'
        self.columnNameList[ 988] = 'AKZ'
        self.columnNameList[ 989] = 'ALA'
        self.columnNameList[ 990] = 'ALB'
        self.columnNameList[ 991] = 'ALC'
        self.columnNameList[ 992] = 'ALD'
        self.columnNameList[ 993] = 'ALE'
        self.columnNameList[ 994] = 'ALF'
        self.columnNameList[ 995] = 'ALG'
        self.columnNameList[ 996] = 'ALH'
        self.columnNameList[ 997] = 'ALI'
        self.columnNameList[ 998] = 'ALJ'
        self.columnNameList[ 999] = 'ALK'
        self.columnNameList[1000] = 'ALL'
        self.columnNameList[1001] = 'ALM'
        self.columnNameList[1002] = 'ALN'
        self.columnNameList[1003] = 'ALO'
        self.columnNameList[1004] = 'ALP'
        self.columnNameList[1005] = 'ALQ'
        self.columnNameList[1006] = 'ALR'
        self.columnNameList[1007] = 'ALS'
        self.columnNameList[1008] = 'ALT'
        self.columnNameList[1009] = 'ALU'
        self.columnNameList[1010] = 'ALV'
        self.columnNameList[1011] = 'ALW'
        self.columnNameList[1012] = 'ALX'
        self.columnNameList[1013] = 'ALY'
        self.columnNameList[1014] = 'ALZ'
        self.columnNameList[1015] = 'AMA'
        self.columnNameList[1016] = 'AMB'
        self.columnNameList[1017] = 'AMC'
        self.columnNameList[1018] = 'AMD'
        self.columnNameList[1019] = 'AME'
        self.columnNameList[1020] = 'AMF'
        self.columnNameList[1021] = 'AMG'
        self.columnNameList[1022] = 'AMH'
        self.columnNameList[1023] = 'AMI'
        self.columnNameList[1024] = 'AMJ'
        self.columnNameList[1025] = 'AMK'
        self.columnNameList[1026] = 'AML'
        self.columnNameList[1027] = 'AMM'
        self.columnNameList[1028] = 'AMN'
        self.columnNameList[1029] = 'AMO'
        self.columnNameList[1030] = 'AMP'
        self.columnNameList[1031] = 'AMQ'
        self.columnNameList[1032] = 'AMR'
        self.columnNameList[1033] = 'AMS'
        self.columnNameList[1034] = 'AMT'
        self.columnNameList[1035] = 'AMU'
        self.columnNameList[1036] = 'AMV'
        self.columnNameList[1037] = 'AMW'
        self.columnNameList[1038] = 'AMX'
        self.columnNameList[1039] = 'AMY'
        self.columnNameList[1040] = 'AMZ'
        self.columnNameList[1041] = 'ANA'
        self.columnNameList[1042] = 'ANB'
        self.columnNameList[1043] = 'ANC'
        self.columnNameList[1044] = 'AND'
        self.columnNameList[1045] = 'ANE'
        self.columnNameList[1046] = 'ANF'
        self.columnNameList[1047] = 'ANG'
        self.columnNameList[1048] = 'ANH'
        self.columnNameList[1049] = 'ANI'
        self.columnNameList[1050] = 'ANJ'
        self.columnNameList[1051] = 'ANK'
        self.columnNameList[1052] = 'ANL'
        self.columnNameList[1053] = 'ANM'
        self.columnNameList[1054] = 'ANN'
        self.columnNameList[1055] = 'ANO'
        self.columnNameList[1056] = 'ANP'
        self.columnNameList[1057] = 'ANQ'
        self.columnNameList[1058] = 'ANR'
        self.columnNameList[1059] = 'ANS'
        self.columnNameList[1060] = 'ANT'
        self.columnNameList[1061] = 'ANU'
        self.columnNameList[1062] = 'ANV'
        self.columnNameList[1063] = 'ANW'
        self.columnNameList[1064] = 'ANX'
        self.columnNameList[1065] = 'ANY'
        self.columnNameList[1066] = 'ANZ'
        self.columnNameList[1067] = 'AOA'
        self.columnNameList[1068] = 'AOB'
        self.columnNameList[1069] = 'AOC'
        self.columnNameList[1070] = 'AOD'
        self.columnNameList[1071] = 'AOE'
        self.columnNameList[1072] = 'AOF'
        self.columnNameList[1073] = 'AOG'
        self.columnNameList[1074] = 'AOH'
        self.columnNameList[1075] = 'AOI'
        self.columnNameList[1076] = 'AOJ'
        self.columnNameList[1077] = 'AOK'
        self.columnNameList[1078] = 'AOL'
        self.columnNameList[1079] = 'AOM'
        self.columnNameList[1080] = 'AON'
        self.columnNameList[1081] = 'AOO'
        self.columnNameList[1082] = 'AOP'
        self.columnNameList[1083] = 'AOQ'
        self.columnNameList[1084] = 'AOR'
        self.columnNameList[1085] = 'AOS'
        self.columnNameList[1086] = 'AOT'
        self.columnNameList[1087] = 'AOU'
        self.columnNameList[1088] = 'AOV'
        self.columnNameList[1089] = 'AOW'
        self.columnNameList[1090] = 'AOX'
        self.columnNameList[1091] = 'AOY'
        self.columnNameList[1092] = 'AOZ'
        self.columnNameList[1093] = 'APA'
        self.columnNameList[1094] = 'APB'
        self.columnNameList[1095] = 'APC'
        self.columnNameList[1096] = 'APD'
        self.columnNameList[1097] = 'APE'
        self.columnNameList[1098] = 'APF'
        self.columnNameList[1099] = 'APG'
        self.columnNameList[1100] = 'APH'
        self.columnNameList[1101] = 'API'
        self.columnNameList[1102] = 'APJ'
        self.columnNameList[1103] = 'APK'
        self.columnNameList[1104] = 'APL'
        self.columnNameList[1105] = 'APM'
        self.columnNameList[1106] = 'APN'
        self.columnNameList[1107] = 'APO'
        self.columnNameList[1108] = 'APP'
        self.columnNameList[1109] = 'APQ'
        self.columnNameList[1110] = 'APR'
        self.columnNameList[1111] = 'APS'
        self.columnNameList[1112] = 'APT'
        self.columnNameList[1113] = 'APU'
        self.columnNameList[1114] = 'APV'
        self.columnNameList[1115] = 'APW'
        self.columnNameList[1116] = 'APX'
        self.columnNameList[1117] = 'APY'
        self.columnNameList[1118] = 'APZ'
        self.columnNameList[1119] = 'AQA'
        self.columnNameList[1120] = 'AQB'
        self.columnNameList[1121] = 'AQC'
        self.columnNameList[1122] = 'AQD'
        self.columnNameList[1123] = 'AQE'
        self.columnNameList[1124] = 'AQF'
        self.columnNameList[1125] = 'AQG'
        self.columnNameList[1126] = 'AQH'
        self.columnNameList[1127] = 'AQI'
        self.columnNameList[1128] = 'AQJ'
        self.columnNameList[1129] = 'AQK'
        self.columnNameList[1130] = 'AQL'
        self.columnNameList[1131] = 'AQM'
        self.columnNameList[1132] = 'AQN'
        self.columnNameList[1133] = 'AQO'
        self.columnNameList[1134] = 'AQP'
        self.columnNameList[1135] = 'AQQ'
        self.columnNameList[1136] = 'AQR'
        self.columnNameList[1137] = 'AQS'
        self.columnNameList[1138] = 'AQT'
        self.columnNameList[1139] = 'AQU'
        self.columnNameList[1140] = 'AQV'
        self.columnNameList[1141] = 'AQW'
        self.columnNameList[1142] = 'AQX'
        self.columnNameList[1143] = 'AQY'
        self.columnNameList[1144] = 'AQZ'
        self.columnNameList[1145] = 'ARA'
        self.columnNameList[1146] = 'ARB'
        self.columnNameList[1147] = 'ARC'
        self.columnNameList[1148] = 'ARD'
        self.columnNameList[1149] = 'ARE'
        self.columnNameList[1150] = 'ARF'
        self.columnNameList[1151] = 'ARG'
        self.columnNameList[1152] = 'ARH'
        self.columnNameList[1153] = 'ARI'
        self.columnNameList[1154] = 'ARJ'
        self.columnNameList[1155] = 'ARK'
        self.columnNameList[1156] = 'ARL'
        self.columnNameList[1157] = 'ARM'
        self.columnNameList[1158] = 'ARN'
        self.columnNameList[1159] = 'ARO'
        self.columnNameList[1160] = 'ARP'
        self.columnNameList[1161] = 'ARQ'
        self.columnNameList[1162] = 'ARR'
        self.columnNameList[1163] = 'ARS'
        self.columnNameList[1164] = 'ART'
        self.columnNameList[1165] = 'ARU'
        self.columnNameList[1166] = 'ARV'
        self.columnNameList[1167] = 'ARW'
        self.columnNameList[1168] = 'ARX'
        self.columnNameList[1169] = 'ARY'
        self.columnNameList[1170] = 'ARZ'
        self.columnNameList[1171] = 'ASA'
        self.columnNameList[1172] = 'ASB'
        self.columnNameList[1173] = 'ASC'
        self.columnNameList[1174] = 'ASD'
        self.columnNameList[1175] = 'ASE'
        self.columnNameList[1176] = 'ASF'
        self.columnNameList[1177] = 'ASG'
        self.columnNameList[1178] = 'ASH'
        self.columnNameList[1179] = 'ASI'
        self.columnNameList[1180] = 'ASJ'
        self.columnNameList[1181] = 'ASK'
        self.columnNameList[1182] = 'ASL'
        self.columnNameList[1183] = 'ASM'
        self.columnNameList[1184] = 'ASN'
        self.columnNameList[1185] = 'ASO'
        self.columnNameList[1186] = 'ASP'
        self.columnNameList[1187] = 'ASQ'
        self.columnNameList[1188] = 'ASR'
        self.columnNameList[1189] = 'ASS'
        self.columnNameList[1190] = 'AST'
        self.columnNameList[1191] = 'ASU'
        self.columnNameList[1192] = 'ASV'
        self.columnNameList[1193] = 'ASW'
        self.columnNameList[1194] = 'ASX'
        self.columnNameList[1195] = 'ASY'
        self.columnNameList[1196] = 'ASZ'
        self.columnNameList[1197] = 'ATA'
        self.columnNameList[1198] = 'ATB'
        self.columnNameList[1199] = 'ATC'
        self.columnNameList[1200] = 'ATD'
        self.columnNameList[1201] = 'ATE'
        self.columnNameList[1202] = 'ATF'
        self.columnNameList[1203] = 'ATG'
        self.columnNameList[1204] = 'ATH'
        self.columnNameList[1205] = 'ATI'
        self.columnNameList[1206] = 'ATJ'
        self.columnNameList[1207] = 'ATK'
        self.columnNameList[1208] = 'ATL'
        self.columnNameList[1209] = 'ATM'
        self.columnNameList[1210] = 'ATN'
        self.columnNameList[1211] = 'ATO'
        self.columnNameList[1212] = 'ATP'
        self.columnNameList[1213] = 'ATQ'
        self.columnNameList[1214] = 'ATR'
        self.columnNameList[1215] = 'ATS'
        self.columnNameList[1216] = 'ATT'
        self.columnNameList[1217] = 'ATU'
        self.columnNameList[1218] = 'ATV'
        self.columnNameList[1219] = 'ATW'
        self.columnNameList[1220] = 'ATX'
        self.columnNameList[1221] = 'ATY'
        self.columnNameList[1222] = 'ATZ'
        self.columnNameList[1223] = 'AUA'
        self.columnNameList[1224] = 'AUB'
        self.columnNameList[1225] = 'AUC'
        self.columnNameList[1226] = 'AUD'
        self.columnNameList[1227] = 'AUE'
        self.columnNameList[1228] = 'AUF'
        self.columnNameList[1229] = 'AUG'
        self.columnNameList[1230] = 'AUH'
        self.columnNameList[1231] = 'AUI'
        self.columnNameList[1232] = 'AUJ'
        self.columnNameList[1233] = 'AUK'
        self.columnNameList[1234] = 'AUL'
        self.columnNameList[1235] = 'AUM'
        self.columnNameList[1236] = 'AUN'
        self.columnNameList[1237] = 'AUO'
        self.columnNameList[1238] = 'AUP'
        self.columnNameList[1239] = 'AUQ'
        self.columnNameList[1240] = 'AUR'
        self.columnNameList[1241] = 'AUS'
        self.columnNameList[1242] = 'AUT'
        self.columnNameList[1243] = 'AUU'
        self.columnNameList[1244] = 'AUV'
        self.columnNameList[1245] = 'AUW'
        self.columnNameList[1246] = 'AUX'
        self.columnNameList[1247] = 'AUY'
        self.columnNameList[1248] = 'AUZ'
        self.columnNameList[1249] = 'AVA'
        self.columnNameList[1250] = 'AVB'
        self.columnNameList[1251] = 'AVC'
        self.columnNameList[1252] = 'AVD'
        self.columnNameList[1253] = 'AVE'
        self.columnNameList[1254] = 'AVF'
        self.columnNameList[1255] = 'AVG'
        self.columnNameList[1256] = 'AVH'
        self.columnNameList[1257] = 'AVI'
        self.columnNameList[1258] = 'AVJ'
        self.columnNameList[1259] = 'AVK'
        self.columnNameList[1260] = 'AVL'
        self.columnNameList[1261] = 'AVM'
        self.columnNameList[1262] = 'AVN'
        self.columnNameList[1263] = 'AVO'
        self.columnNameList[1264] = 'AVP'
        self.columnNameList[1265] = 'AVQ'
        self.columnNameList[1266] = 'AVR'
        self.columnNameList[1267] = 'AVS'
        self.columnNameList[1268] = 'AVT'
        self.columnNameList[1269] = 'AVU'
        self.columnNameList[1270] = 'AVV'
        self.columnNameList[1271] = 'AVW'
        self.columnNameList[1272] = 'AVX'
        self.columnNameList[1273] = 'AVY'
        self.columnNameList[1274] = 'AVZ'
        self.columnNameList[1275] = 'AWA'
        self.columnNameList[1276] = 'AWB'
        self.columnNameList[1277] = 'AWC'
        self.columnNameList[1278] = 'AWD'
        self.columnNameList[1279] = 'AWE'
        self.columnNameList[1280] = 'AWF'
        self.columnNameList[1281] = 'AWG'
        self.columnNameList[1282] = 'AWH'
        self.columnNameList[1283] = 'AWI'
        self.columnNameList[1284] = 'AWJ'
        self.columnNameList[1285] = 'AWK'
        self.columnNameList[1286] = 'AWL'
        self.columnNameList[1287] = 'AWM'
        self.columnNameList[1288] = 'AWN'
        self.columnNameList[1289] = 'AWO'
        self.columnNameList[1290] = 'AWP'
        self.columnNameList[1291] = 'AWQ'
        self.columnNameList[1292] = 'AWR'
        self.columnNameList[1293] = 'AWS'
        self.columnNameList[1294] = 'AWT'
        self.columnNameList[1295] = 'AWU'
        self.columnNameList[1296] = 'AWV'
        self.columnNameList[1297] = 'AWW'
        self.columnNameList[1298] = 'AWX'
        self.columnNameList[1299] = 'AWY'
        self.columnNameList[1300] = 'AWZ'
        self.columnNameList[1301] = 'AXA'
        self.columnNameList[1302] = 'AXB'
        self.columnNameList[1303] = 'AXC'
        self.columnNameList[1304] = 'AXD'
        self.columnNameList[1305] = 'AXE'
        self.columnNameList[1306] = 'AXF'
        self.columnNameList[1307] = 'AXG'
        self.columnNameList[1308] = 'AXH'
        self.columnNameList[1309] = 'AXI'
        self.columnNameList[1310] = 'AXJ'
        self.columnNameList[1311] = 'AXK'
        self.columnNameList[1312] = 'AXL'
        self.columnNameList[1313] = 'AXM'
        self.columnNameList[1314] = 'AXN'
        self.columnNameList[1315] = 'AXO'
        self.columnNameList[1316] = 'AXP'
        self.columnNameList[1317] = 'AXQ'
        self.columnNameList[1318] = 'AXR'
        self.columnNameList[1319] = 'AXS'
        self.columnNameList[1320] = 'AXT'
        self.columnNameList[1321] = 'AXU'
        self.columnNameList[1322] = 'AXV'
        self.columnNameList[1323] = 'AXW'
        self.columnNameList[1324] = 'AXX'
        self.columnNameList[1325] = 'AXY'
        self.columnNameList[1326] = 'AXZ'
        self.columnNameList[1327] = 'AYA'
        self.columnNameList[1328] = 'AYB'
        self.columnNameList[1329] = 'AYC'
        self.columnNameList[1330] = 'AYD'
        self.columnNameList[1331] = 'AYE'
        self.columnNameList[1332] = 'AYF'
        self.columnNameList[1333] = 'AYG'
        self.columnNameList[1334] = 'AYH'
        self.columnNameList[1335] = 'AYI'
        self.columnNameList[1336] = 'AYJ'
        self.columnNameList[1337] = 'AYK'
        self.columnNameList[1338] = 'AYL'
        self.columnNameList[1339] = 'AYM'
        self.columnNameList[1340] = 'AYN'
        self.columnNameList[1341] = 'AYO'
        self.columnNameList[1342] = 'AYP'
        self.columnNameList[1343] = 'AYQ'
        self.columnNameList[1344] = 'AYR'
        self.columnNameList[1345] = 'AYS'
        self.columnNameList[1346] = 'AYT'
        self.columnNameList[1347] = 'AYU'
        self.columnNameList[1348] = 'AYV'
        self.columnNameList[1349] = 'AYW'
        self.columnNameList[1350] = 'AYX'
        self.columnNameList[1351] = 'AYY'
        self.columnNameList[1352] = 'AYZ'
        self.columnNameList[1353] = 'AZA'
        self.columnNameList[1354] = 'AZB'
        self.columnNameList[1355] = 'AZC'
        self.columnNameList[1356] = 'AZD'
        self.columnNameList[1357] = 'AZE'
        self.columnNameList[1358] = 'AZF'
        self.columnNameList[1359] = 'AZG'
        self.columnNameList[1360] = 'AZH'
        self.columnNameList[1361] = 'AZI'
        self.columnNameList[1362] = 'AZJ'
        self.columnNameList[1363] = 'AZK'
        self.columnNameList[1364] = 'AZL'
        self.columnNameList[1365] = 'AZM'
        self.columnNameList[1366] = 'AZN'
        self.columnNameList[1367] = 'AZO'
        self.columnNameList[1368] = 'AZP'
        self.columnNameList[1369] = 'AZQ'
        self.columnNameList[1370] = 'AZR'
        self.columnNameList[1371] = 'AZS'
        self.columnNameList[1372] = 'AZT'
        self.columnNameList[1373] = 'AZU'
        self.columnNameList[1374] = 'AZV'
        self.columnNameList[1375] = 'AZW'
        self.columnNameList[1376] = 'AZX'
        self.columnNameList[1377] = 'AZY'
        self.columnNameList[1378] = 'AZZ'
        
        return


class ExcelLib(ECell):
    workbook:excel.Workbook
    sheetName:str

    def __init__(self)->None:
        super(ExcelLib, self).__init__()
        self.FileSysProcess = FileSysProcess()
        self.sheetName = ''
        self.excelFileAddress = ''
        return
    
    def createExcelFile(self, excelFileAddress:str)->bool:
        """
        --------------------------------------------------
        ExcelFile新規作成\n
        【引数 】\n
            excelFileAddress:ExcelFile格納場所\n
        【戻り値】\n
            bool:処理結果\n
        --------------------------------------------------
        """
        bResult:bool =  True
        try:
            self.excelFileAddress = excelFileAddress
            self.workbook = excel.Workbook()
            self.sheetName = self.workbook.sheetnames[0]
            self.workbook.save(excelFileAddress)
        except Exception as e:
            print('Failure to create excelFile:', excelFileAddress)
            bResult = False
        return bResult

    def openExcelFile(self, excelFileAddress:str, read_only:bool = False)->bool:
        """
        --------------------------------------------------
        ExcelFile開く\n
        【引数 】\n
            excelFileAddress:ExcelFile格納場所\n
        【戻り値】\n
            bool:処理結果\n
        --------------------------------------------------
        """
        bResult:bool =  True
        try:
            self.excelFileAddress = excelFileAddress
            self.workbook = excel.load_workbook(excelFileAddress, read_only=read_only)
            self.sheetName = self.workbook.sheetnames[0]
        except Exception as e:
            print('Failure to open excelFile:', excelFileAddress)
            bResult = False
        return bResult

    
    def setWorkSheet(self, workbook:excel.Workbook|None = None, sheetName:str = '', sheetSearchFlg = False)->bool:
        """
        --------------------------------------------------
        WorkSheet設定\n
        【引数 】\n
            workbook:ExcelFileオブジェクト\n
            sheetName:シート名称\n
            sheetSearchFlg:検索方式(False:完全一致, True:シート名称に指定文字列含む)
        【戻り値】\n
            bool:処理結果\n
        --------------------------------------------------
        """
        if workbook is not None:
            self.workbook = workbook
        
        if self.workbook is None:
            print('workbook is None')
            return False

        if sheetName == '':
            self.sheetName = self.workbook.sheetnames[0]
            return True
        if sheetSearchFlg == False:
            #完全一致
            if sheetName in self.workbook.sheetnames:
                self.sheetName = sheetName
                return True
        else:
            for curSheetName in self.workbook.sheetnames:
                if curSheetName.find(sheetName) >= 0:
                    self.sheetName = curSheetName
                    return True
        print('sheetName is not in excelSheetList')
        return False

    def save(self, excelFileAddress:str = '') ->bool:
        """
        --------------------------------------------------
        Excelファイル内容保存処理\n
        【引数 】\n
            excelFileAddress:ExcelFile格納先\n
        【戻り値】\n
            bool:処理結果\n
        --------------------------------------------------
        """
        if excelFileAddress == '':
            excelFileAddress = self.excelFileAddress

        bResult =  True
        try:
            self.workbook.save(excelFileAddress)
        except Exception as e:
            print(f'excelFileAddress({excelFileAddress}) is not exsited??')
            bResult = False
        return bResult

    
    def modifySheetName(self,dstSheetName:str, srcSheetName:str= '')->bool:
        """
        --------------------------------------------------
        Excelファイルシート名称修正処理\n
        【引数 】\n
            dstSheetName:修正後シートファイル名称\n
            srcSheetName:修正前シートファイル名称\n
        【戻り値】\n
            bool:処理結果\n
        --------------------------------------------------
        """
        if self.workbook is None:
            print('workbook is None')
            return False

        if dstSheetName == '':
            print('dstSheetName is Null')
            return False
        if srcSheetName != '':
            if srcSheetName in self.workbook.sheetnames:
                self.sheetName = srcSheetName
            else:
                print(f'srcSheetName({srcSheetName}) is not exsited in excelSheetList')
                return False

        self.workbook[self.sheetName].title = dstSheetName
        self.sheetName = dstSheetName
        return True
    
    def createSheet(self, sheetName:str= '')->bool:
        if self.workbook is None:
            print('workbook is None')
            return False
        
        if sheetName == '':
            sheetIndex = len(self.workbook.sheetnames)
            self.workbook.create_sheet()
            self.sheetName = self.workbook.sheetnames[sheetIndex]
        else:
            sheetIndex = len(self.workbook.sheetnames)
            self.workbook.create_sheet(index = sheetIndex, title= sheetName)
            self.sheetName = sheetName
        return True
        


    def setColumnsWidth(self,columnIndex:int, endColumnIndex:int = 0, withValue:float|int = 3)->bool:
        if self.workbook is None:
            print('workbook is None')
            return False

        worksheet = self.workbook[self.sheetName]
        if columnIndex <= 0:
            return False
        if endColumnIndex == 0:
            endColumnIndex = columnIndex
        if endColumnIndex < columnIndex:
            return False
        while(columnIndex <= endColumnIndex):
            worksheet.column_dimensions[self.getColumnName(columnIndex)].width = str(withValue)
            columnIndex += 1
        return True
    
    # 罫線(外枠)を設定
    def setBorder(self,startRowIndex:int, endRowIndex:int, startColumnIndex:int, endColumnIndex:int, border:Border = defaultborder)->None:

        worksheet = self.workbook[self.sheetName]
        for rowIndex in range(startRowIndex,endRowIndex + 1):
            for columnIndex in range(startColumnIndex,endColumnIndex + 1):
                worksheet.cell(row=rowIndex ,column=columnIndex).border = border

    #背景色設定
    def setBackGroundColor(self,rowIndex:int,startColumnIndex:int, endColumnIndex:int, colorValue:str)->None:
        
        fillColor = PatternFill(patternType=FILL_SOLID, fgColor=colorValue, bgColor=colorValue)
        worksheet = self.workbook[self.sheetName]
        for columnIndex in range(startColumnIndex, endColumnIndex + 1):
            cellPos = self.getColumnName(columnIndex) + str(rowIndex)
            worksheet[cellPos].fill = fillColor
        return
    
    def setBackGroundColorByCellValue(self,startRowIndex:int, endRowIndex:int,startColumnIndex:int, endColumnIndex:int, cellValue:str, colorValue:str)->None:
        
        worksheet = self.workbook[self.sheetName]

        for rowIndex in range(startRowIndex,endRowIndex + 1):
            for columnIndex in range(startColumnIndex,endColumnIndex + 1):
                cellPos = self.getColumnName(columnIndex) + str(rowIndex)
                if worksheet[cellPos].value == cellValue:
                    self.setBackGroundColor(rowIndex, columnIndex, columnIndex, colorValue)
        return

    def addCellValue(self, rowIndex:int, columnIndex:int,  dataValue:int|bool|str)->None:
        worksheet = self.workbook[self.sheetName]
        cellPos = self.getColumnName(columnIndex) + str(rowIndex)
        worksheet[cellPos] = str(dataValue)
        return
    
    def mergeCells(self, startRowIndex:int, endRowIndex:int,startColumnIndex:int, endColumnIndex:int)->None:
        worksheet = self.workbook[self.sheetName]
        worksheet.merge_cells(start_row= startRowIndex, start_column= startColumnIndex, end_row=endRowIndex, end_column= endColumnIndex)
        return
        
